### ISSUE TITLE
Não está aparecendo as configurações no Painel

### ISSUE THREAD

**Issue by helitonrudolf** [ditointernet/dito-magento#9]
No arquivo app/code/local//Dito/DitoTracking/etc/system.xml existe um field que está sendo fechado incorretamente. <blog_index> .... <blog_index_l>

Acredito que isto esteja dando erro no módulo pois quando corrigi apareceu normalmente no painel 

Magento: 1.9.3.7

Att.

![Captura de tela de 2019-05-29 11-14-11](https://user-images.githubusercontent.com/32688411/58564426-483d4b00-8203-11e9-9628-545fbf82a65b.png)

**Comment by tannusesquerdo** [comment]
Olá @helitonrudolf.

Obrigado pela issue.
Vamos fazer as devidas correções.

Att,

Tannus Esquerdo

**Comment by tannusesquerdo** [comment]
Closed #10 .
